export const SET_USER = "SET_USER";
export const DELETE_USER = "DELETE_USER";
export const AUTHENTICATED_SUCCESSFULLY = 'AUTHENTICATED_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
export const SET_ANIMALS = 'SET_ANIMALS'
export const ANIMAL_CATEGORY = 'ANIMAL_CATEGORY'
export const PAY_FILTER = 'PAY_FILTER'
export const SET_FILTERED_ANIMALS = 'SET_FILTERED_ANIMALS'

