export const SET_USER = "SET_USER";
export const DELETE_USER = "DELETE_USER";
export const AUTHENTICATED_SUCCESSFULLY = 'AUTHENTICATED_SUCCESSFULLY';
export const LOGOUT = 'LOGOUT';
export const SET_ANIMALS = 'SET_ANIMALS'

export const ANIMAL_CATEGORY = 'ANIMAL_CATEGORY'
export const PRICE_FILTER = 'PRICE_FILTER'
export const PAY_FILTER = 'PAY_FILTER'
export const ADD_ANIMAL = 'ADD_ANIMAL'
export const AGE_FILTER = 'AGE_FILTER'
export const GENDER_FILTER = 'GENDER_FILTER'
export const HAIR_FILTER = 'HAIR_FILTER'

export const WEIGHT_FILTER = 'WEIGHT_FILTER'
export const GUIDE_FILTER = 'GUIDE_FILTER'
export const WAR_FILTER = 'WAR_FILTER'
export const SUFFER_FILTER = 'SUFFER_FILTER'
export const CONDITION_FILTER = 'CONDITION_FILTER'
export const CHILDREN_FILTER = 'CHILDREN_FILTER'
export const APARTMENT_FILTER = 'APARTMENT_FILTER'
export const CLEAN_FILTER = 'CLEAN_FILTER'
